name: manual
on:
  workflow_dispatch:
    inputs:
      env:
        description: "env"
        required: true
        type: choice
        options:
          - dev
          - stg
          - prod

jobs:
  show-env:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo ${{ inputs.env }}

  print-prev-month:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - run: pip3 install -r requirements.txt
      - run: python3 main.py
