name: manual
on:
  workflow_dispatch:
    inputs:
      year:
        description: "year"
        required: true
        type: string
        default: "2025"
      month:
        description: "month"
        required: true
        type: string
      day:
        description: "month"
        required: true
        type: string
        default: "*"

jobs:
  print-input-time:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - run: pip3 install -r requirements.txt
      - run: python3 manual.py -y "${{ inputs.year }}" -m "${{ inputs.month }}" -d "${{ inputs.day }}"
      - uses: actions/upload-artifact@v4
        with:
          name: report
          path: |
            report.json
