name: scheduled
on:
  schedule:
    - cron: "30 8 28 * *" 

jobs:
  show-env:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo ${{ inputs.env }}

  print-prev-month:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - run: pip3 install -r requirements.txt
      - run: python3 scheduled.py
      - uses: actions/upload-artifact@v4
        with:
          name: report
          path: |
            report.json
